accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='accounts'
urlpatterns = [
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register/',register_view,name='register'),
]

mainsite/urls.py
from django.contrib import admin
from django.urls import path
from home.views import homeview
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homeview,name='home'),
    path('post/',include('post.urls')),
    path('accounts/',include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns +=('django.views.static',(r'^media/(?P<path>.*)','serve',{'document_root':settings.MEDIA_ROOT}), )

post/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='post'
urlpatterns = [
    path('index/',post_index,name='index'),
    path('create/',post_crate,name='create'),
    path('<slug:slug>/',post_detail,name='detail'),
    path('<slug:slug>/update/',post_update,name='update'),
    path('<slug:slug>/delete/',post_delete,name='delete'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render,HttpResponse
# Create your views here.
def homeview(request):
    if request.user.is_authenticated:
        context={
        'Durum':'Luuwa',


        }
    else:
        context={
        'Durum':'Misafir',


        }
    return render(request,'home.html',context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="tr">
<head>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
  <meta charset="utf-8" name="viewport" content="width=device-width, inital-scale=1"></meta>
  <title>{% block title %}BASE{% endblock %}</title>
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">


</head>
<a>
    {% include 'header.html'  %}
    {% include 'messages.html' %}
    {% block body %}

    {% endblock %}
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>




</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">MainSite</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
                <li><a href="{% url 'post:create' %}">Post ekle</a></li>

              {% endif %}
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                {% if request.user.is_authenticated %}
                  <li><a href="{% url 'accounts:logout' %}">Çıkış Yap</a></li>
                {% else %}
                  <li><a href="{% url 'accounts:login' %}">Giriş Yap</a></li>
                  <li><a href="{% url 'accounts:register' %}">Üye ol</a></li>
                {% endif %}
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% block title %} Ana Sayfa - {{block.super}} {% endblock %}
{% block body %}


    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:red;height:50px;margin-bottom:15px;">SUTUN 1</div>
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:blue;height:50px;margin-bottom:15px;">SUTUN 2</div>
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:green;height:50px;margin-bottom:15px;">SUTUN 3</div>
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:yellow;height:50px;margin-bottom:15px;">SUTUN 4</div>
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:purple;height:50px;margin-bottom:15px;">SUTUN 5</div>
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:gray;height:50px;margin-bottom:15px;">SUTUN 6</div>
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:black;height:50px;margin-bottom:15px;">SUTUN 7</div>
        <div class="col-md-3 col-sm-6 col-xs-12"style="background-color:white;height:50px;margin-bottom:15px;">SUTUN 8</div>
      </div>
    </div>
    {% if request.user.is_authenticated %}
      <h3> Hoş Geldin {{ request.user.get_full_name }} </h3>
    {% endif %}
{% endblock %}

templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

templates/messagesdanger.html
{% if messages %}
      {% for message in messages %}
        <div class="alert alert-success" role="alert">
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        </div>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
{% endif %}